initial_robot_configuration:
  ###############################
  # Initial robot configuration #
  ###############################
  com: [0.0040283, -0.000119648, 0.51123]
  amom: [0.0, 0.0, 0.0]
  lmom: [0.0, 0.0, 0.0]
  eef_ctrl: # percentage of robot weight force (mg)
    eef_frc_al: [0.0, 0.0, 0.25]
    eef_frc_ar: [0.0, 0.0, 0.25]
    eef_frc_bl: [0.0, 0.0, 0.25]
    eef_frc_br: [0.0, 0.0, 0.25]  
  eef_pose:
    # activation(1) /  pos(3) / quat(4)
    eef_al: [1.0, -0.115268, 0.128074, 0.312233, 0.703542, -0.413624, 0.573433, -0.0715449]
    eef_ar: [1.0, -0.112609, -0.123463, 0.36282, 0.0210488, 0.622618, -0.335185, 0.706792]
    eef_bl: [1.0, -0.120027, 0.135158, 0.66661, 0.660985, -0.158096, 0.710569, 0.182196]
    eef_br: [1.0, -0.118635, -0.128237, 0.66165, 0.388958, 0.668939, -0.0959493, 0.62612]
  eef_env:
    # fricoeff(1) / magnetic force(3)
    eef_al: [0.7, 0.0, 0.0, 80]
    eef_ar: [0.7, 0.0, 0.0, 80]
    eef_bl: [0.7, 0.0, 0.0, 80]
    eef_br: [0.7, 0.0, 0.0, 80]

contact_plan:
  ######################
  # Contact parameters #
  ######################
  num_contacts: [1, 1, 2, 1] # swing foot=br, lowfriction foot=ar
  # timeini,end(2) /  pos(3) / quat(4) / contacttype(0=free,1=flat,2=full) /friction_coeff(1) / magnetic_force(1) / 
  eefcnt_al: 
    cnt0: [0.0, 0.71, -0.115268, 0.128074, 0.312233, 0.703542, -0.413624, 0.573433, -0.0715449, 1.0, 0.7, 80]
  eefcnt_ar: 
    cnt0: [0.0, 0.71, -0.112609, -0.123463, 0.36282, 0.0210488, 0.622618, -0.335185, 0.706792, 1.0, 0.7, 80]
  eefcnt_bl: 
    cnt0: [0.0, 0.3, -0.120027, 0.135158, 0.66661, 0.660985, -0.158096, 0.710569, 0.182196, 1.0, 0.7, 80]
    cnt1: [0.6, 0.71, -0.123669, 0.142625, 0.714186, 0.597186, 0.0291732, 0.706568, 0.378523, 1.0, 0.7, 80]
  eefcnt_br: 
    cnt0: [0.0, 0.71, -0.118635, -0.128237, 0.66165, 0.388958, 0.668939, -0.0959493, 0.62612, 1.0, 0.7, 80]

optimization:
    #######################
    # Dynamics parameters #
    #######################
    heuristic: SoftConstraint # SoftConstraint  # Types: TrustRegion, SoftConstraint
    n_act_eefs: 4    
    external_force: [0.00, 0.00, 0.00]
    com_goal: [0.00227327, -0.000164365, 0.526148]
    num_com_viapoints: 0 #TODO:will be depricated
    com_viapoints:
        via0: [0.6,    0.022184,   0.014779,   0.150793]

    #####################
    # Timing parameters #
    #####################
    time_step: 0.05
    time_horizon: 0.71
    max_time_iterations: 1000
    max_time_residual_tolerance: 1e-3
    min_time_residual_improvement: 1e-5

    ############################
    # Configuration parameters #
    ############################
    gravity: 9.81
    robot_mass: 5.78357    
    friction_cone: LinearCone  # Types: LinearCone, SocCone #
    torque_range: [-0.1, 0.1]
    eef_offset_al: [ 0.0,  0.00,  0.00 ]
    eef_offset_ar: [ 0.0,  0.00,  0.00 ]
    eef_offset_bl: [ 0.0,  0.00,  0.00 ]
    eef_offset_br: [ 0.0,  0.00,  0.00 ]
    max_eef_lengths: [0.5,  0.5,  0.5,  0.5]

    ####################
    # Dynamics weights #
    ####################
    w_trq_leg:       1.000
    w_com:           [ 500000,  500000,  500000]
    w_amom:          [ 0.500,  0.500,  0.500]
    w_lmom:          [ 0.010,  0.005,  0.001]
    w_amomd:         [ 2.0,  2.5,  2.0] # rate of amom
    w_lmomd:         [ 0.015,  0.015,  0.015] # rate of lmom
    w_amom_final:    [ 100.00,  100.00,  100.00]
    w_lmom_final:    [ 100.00,  100.00,  100.00]
    w_com_via:       [ 0.000,  0.000,  0.000]
    w_frc_leg:       [ 0.01,  0.01,  0.01]
    w_dfrc_leg:      [ 0.001,  0.001,  0.001] # rate of forces
    w_amom_track:    [ 1.000,  1.000,  1.000]
    w_lmom_track:    [ 0.100,  0.100,  0.100]

    #######################
    # Storage information #
    #######################
    store_data: True
    storage_path: ExperimentData/TEST_PLANNING_RESULT_1.yaml

    ##################
    # Solver setting #
    ##################
    use_default_solver_setting: True
