initial_robot_configuration:
  ###############################
  # Initial robot configuration #
  ###############################
  com: [-0.00012572, 0.0047999, 0.531909]
  amom: [0.0, 0.0, 0.0]
  lmom: [0.0, 0.0, 0.0]
  eef_ctrl: # percentage of robot weight force (mg)
    eef_frc_al: [0.0, 0.0, 0.25]
    eef_frc_ar: [0.0, 0.0, 0.25]
    eef_frc_bl: [0.0, 0.0, 0.25]
    eef_frc_br: [0.0, 0.0, 0.25] 
  eef_pose:
    # activation(1) /  pos(3) / quat(4)
    eef_al: [1.0, -0.114098, 0.127789, 0.304916, 0.674412, -0.507754, 0.484516, -0.229343]
    eef_ar: [1.0, -0.112402, -0.123109, 0.362891, 0.0208795, 0.622558, -0.335289, 0.7068]
    eef_bl: [1.0, -0.123689, 0.14265, 0.712238, 0.592638, 0.0376139, 0.706109, 0.385714]
    eef_br: [1.0, -0.115568, -0.128577, 0.7077, 0.379942, 0.706435, 0.0307436, 0.596363]
  eef_env:
    # fricoeff(1) / magnetic force(3)
    eef_al: [0.7, 0.0, 0.0, 80]
    eef_ar: [0.7, 0.0, 0.0, 80]
    eef_bl: [0.7, 0.0, 0.0, 80]
    eef_br: [0.7, 0.0, 0.0, 80]

contact_plan:
  ######################
  # Contact parameters #
  ######################
  num_contacts: [2, 1, 1, 1] # swing foot=br, lowfriction foot=ar
  # timeini,end(2) /  pos(3) / quat(4) / contacttype(0=free,1=flat,2=full) /friction_coeff(1) / magnetic_force(1) / 
  eefcnt_al: 
    cnt0: [0.0, 0.3, -0.114098, 0.127789, 0.304916, 0.674412, -0.507754, 0.484516, -0.229343, 1.0, 0.7, 80]
    cnt1: [0.6, 0.71, -0.117728, 0.132333, 0.371469, 0.694832, -0.460975, 0.536176, -0.131247, 1.0, 0.7, 80]
  eefcnt_ar: 
    cnt0: [0.0, 0.71, -0.112402, -0.123109, 0.362891, 0.0208795, 0.622558, -0.335289, 0.7068, 1.0, 0.7, 80]
  eefcnt_bl: 
    cnt0: [0.0, 0.71, -0.123689, 0.14265, 0.712238, 0.592638, 0.0376139, 0.706109, 0.385714, 1.0, 0.7, 80]
  eefcnt_br: 
    cnt0: [0.0, 0.71, -0.115568, -0.128577, 0.7077, 0.379942, 0.706435, 0.0307436, 0.596363, 1.0, 0.7, 80]

optimization:
    #######################
    # Dynamics parameters #
    #######################
    heuristic: SoftConstraint # SoftConstraint  # Types: TrustRegion, SoftConstraint
    n_act_eefs: 4    
    external_force: [0.00, 0.00, 0.00]
    com_goal: [0.00166007, 0.00711315, 0.544877]
    num_com_viapoints: 0 #TODO:will be depricated
    com_viapoints:
        via0: [0.6,    0.022184,   0.014779,   0.150793]

    #####################
    # Timing parameters #
    #####################
    time_step: 0.05
    time_horizon: 0.71
    max_time_iterations: 1000
    max_time_residual_tolerance: 1e-3
    min_time_residual_improvement: 1e-5

    ############################
    # Configuration parameters #
    ############################
    gravity: 9.81
    robot_mass: 5.78357    
    friction_cone: LinearCone  # Types: LinearCone, SocCone #
    torque_range: [-0.1, 0.1]
    eef_offset_al: [ 0.0,  0.00,  0.00 ]
    eef_offset_ar: [ 0.0,  0.00,  0.00 ]
    eef_offset_bl: [ 0.0,  0.00,  0.00 ]
    eef_offset_br: [ 0.0,  0.00,  0.00 ]
    # cop_range_al: [-0.02, 0.02, -0.02, 0.02]
    # cop_range_ar: [-0.02, 0.02, -0.02, 0.02]
    # cop_range_bl: [-0.02, 0.02, -0.02, 0.02]
    # cop_range_br: [-0.02, 0.02, -0.02, 0.02]
    max_eef_lengths: [0.5,  0.5,  0.5,  0.5]

    ####################
    # Dynamics weights #
    ####################
    w_trq_leg:       1.000
    w_com:           [ 500000,  500000,  500000]
    w_amom:          [ 0.500,  0.500,  0.500]
    w_lmom:          [ 0.010,  0.005,  0.001]
    w_amomd:         [ 2.0,  2.5,  2.0] # rate of amom
    w_lmomd:         [ 0.015,  0.015,  0.015] # rate of lmom
    w_amom_final:    [ 100.00,  100.00,  100.00]
    w_lmom_final:    [ 100.00,  100.00,  100.00]
    w_com_via:       [ 0.000,  0.000,  0.000]
    w_frc_leg:       [ 0.01,  0.01,  0.01]
    w_dfrc_leg:      [ 0.001,  0.001,  0.001] # rate of forces
    w_amom_track:    [ 1.000,  1.000,  1.000]
    w_lmom_track:    [ 0.100,  0.100,  0.100]

    #######################
    # Storage information #
    #######################
    store_data: True
    storage_path: ExperimentData/TEST_PLANNING_RESULT_3.yaml

    ##################
    # Solver setting #
    ##################
    use_default_solver_setting: True
